# Generated by Django 4.2.13 on 2024-06-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='car_price',
            new_name='book_price',
        ),
    ]
