# Generated by Django 4.2.13 on 2024-06-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_order_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
    ]
