# Generated by Django 4.2.13 on 2024-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_order_active'),
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='posts.post'),
        ),
    ]
