# Generated by Django 5.0.6 on 2024-06-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_account_no_alter_useraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_no',
            field=models.IntegerField(unique=True),
        ),
    ]
