# Generated by Django 4.2.13 on 2024-06-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='postal_code',
        ),
    ]
